package kr.or.chan.product;

public class ProductDaoSqls {
	public static final int GET_MORE_PRODUCT_COUNT = 4;
	public static final String SELECT_ALL_PRODUCT = ""
		+ "SELECT product.id id"
		+ "		, product.category_id"
		+ "		, product.description"
		+ "     , product.content"
		+ "		, product.event"
		+ "		, product.create_date"
		+ "		, product.modify_date"
		+ "		, product_image.id image_id"
		+ "		, product_image.file_id"
		+ "		, display_info.id display_info_id"
		+ "		, display_info.place_name "
		+ "FROM product "
		+ "JOIN product_image ON product.id = product_image.product_id "
		+ "JOIN display_info ON product.id = display_info.product_id "
		+ "WHERE product_image.type='th' "
		+ "ORDER BY id ASC "
		+ "LIMIT :start, :limit";

	public static final String SELECT_PRODUCT_BY_DISPLAY_ID = ""
		+ "SELECT product.id product_id"
		+ "		, product.category_id"
		+ "		, product.description"
		+ "		, product.content"
		+ "		, product.event"
		+ "		, product.create_date"
		+ "		, product.modify_date"
		+ "		, product_image.type"
		+ "		, product_image.id id"
		+ "		, display_info.place_name"
		+ "		, display_info.place_lot"
		+ " 	, display_info.place_street"
		+ "		, display_info.tel"
		+ "		, display_info_image.file_id "
		+ "FROM product "
		+ "JOIN display_info ON product.id = display_info.product_id "
		+ "JOIN display_info_image ON display_info.id = display_info_image.display_info_id "
		+ "JOIN product_image ON product.id = product_image.product_id "
		+ "WHERE display_info.id = :displayInfoId "
		+ "AND product_image.type='th'";

	public static final String SELECT_PRODUCT_BY_CATEGORY_ID = ""
		+ "SELECT product.id id"
		+ "		, product.category_id"
		+ "		, product.description"
		+ "		, product.content"
		+ "		, product.event"
		+ "		, product.create_date"
		+ "		, product.modify_date"
		+ "		, product_image.file_id"
		+ "		, product_image.id image_id"
		+ "		, display_info.id display_info_id"
		+ "		, display_info.place_name "
		+ "FROM product "
		+ "JOIN product_image ON product.id = product_image.product_id "
		+ "JOIN display_info ON product.id = display_info.product_id "
		+ "WHERE product_image.type='th' "
		+ "AND category_id = :categoryId "
		+ "ORDER BY id ASC "
		+ "LIMIT :start, :limit";

	public static final String SELECT_PRODUCT_BY_DISPLAYINFO_ID = ""
		+ "SELECT display_info.id"
		+ "		, display_info.place_name"
		+ "		, display_info.opening_hours"
		+ "		, product.id product_id"
		+ "		, product.description"
		+ "		, product_image.file_id "
		+ "FROM product "
		+ "JOIN display_info ON product.id = display_info.product_id "
		+ "JOIN product_image ON product.id = product_image.product_id "
		+ "WHERE display_info.id = :displayInfoId "
		+ "AND product_image.type = 'ma'";
}
